console.log('\n')
console.log('              g@NNg,               ')
console.log('            ,@"    `"Bg                           ,,               ')
console.log('           ]@   wg ]]g]@                       ,@P`@@gNM@,               ')
console.log('           $F  ]J@K\'Q$ *@,               ,,,,gP  ``-*$g$$N               ')
console.log('          ,@`    `   ,^  @            ,gP" -*`      ^,gP               ')
console.log('          ]C    `\'"*"   gP        ,g@P]P      ,,,ggN"`               ')
console.log('           %g          ^$PMM$@P$@B@"$F ]@    ""]@               ')
console.log('           ,g@N&`         ]P ]@ ]P ]g   MNgggR"               ')
console.log('       gg@@"              $  ]W \'@  "Nwg,g@P`               ')
console.log('    ,@P`]P                ]g  %g  *Nmg@R"               ')
console.log('    :::      ::::::::   ::::::::      ::::::::    :::     ')
console.log('  :+: :+:   :+:    :+: :+:    :+:    :+:    :+: :+:+:     ')
console.log(' +:+   +:+  +:+    +:+ +:+                 +:+    +:+     ')
console.log('+#++:++#++: +#+    +:+ +#+               +#+      +#+     ')
console.log('+#+     +#+ +#+    +#+ +#+             +#+        +#+     ')
console.log('#+#     #+# #+#    #+# #+#    #+#     #+#         #+#     ') 
console.log('###     ###  ########   ########     ########## #######  ')
console.log('')

require('./day1.js')
require('./day2.js')
require('./day3.js') 
require('./day4.js') 
require('./day5.js')